services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /.*    # capture toutes les routes
        destination: /index.html
